on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x' # or the version you are using

      - name: Restore dependencies and generate lock files
        run: dotnet restore -p:RestorePackagesWithLockFile=True

      - name: Run Semgrep Scan
        run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
